---
# 2017-03-14: MR - trigger SRW container build after fixing radiasoft/sirepo#696 and mrakitin/SRW#35.
# 2017-03-17: MR - add SRW test.
sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
script:
  - curl radia.run | bash -s container-build
